before_install:
- sudo apt-get update
- sudo apt-get install texlive-latex-extra
script:
- mkdir _build
- pdflatex -output-directory _build ./Hello.tex
deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file:
   - ./_build/Hello.pdf
  skip_cleanup: true